language: python
python:
- 3.4.3
services: memcached
env:
  global:
    secure: zkVlw3UPqbmRi/ja4Eczb/yC2tZwc/cAKj1YbqOZVh9BTWiQL5oo2f06svNJfcMl+1LG6K8w9l4OAUpyNsQ+2G2pAlu5W5fQhg2Ok/liQrjDTmI+oq/lRV3NTlNst9gdNa2r3hyIKygLnbaO/X/ToN+Z/xnf+mlazXcCdBupvPNETMIo6G7+dARq0o98WkEJrX5UZFmlM+3D3gi97D23xYBPEWjBdhTg08spw8oOpc7X2l2nUvip//xXucETN07PC9j0ueUGyt16Pi0CM5lJgBAnW56cukf5jXcEEbKeZQP76B1yr8cq9v1wZqsrhI82TSUf5wF39oWzUt8RV6xcl/15XeJkOL8Gj9k2zDlcWGnFhq+nqVUvqi3Ro4XkerxUo/YeqlHzQ5vOG9uCazGkiEcD8b1HmIL60Mrd0O17BDswxw5DBWjbGiGSlAlhzCT1/od6oF7bl2pXTsL0PvTzrJyFzy97nFx1+lI4lA1ZYzgo0juKUMYq9iRt2DFxFU3z5aQ6WPEO87wAueevIS9x7R5tgKL58kqEvHMygpEccGDq7dKALFEmAg3jGzL6/U/62u6RrIA9S5fnpSMg0pzHW7Y3oOeEJzee71XJu5Cb5oC07q5LV6PDxwqP0lwLaBWh4PUGIWzBDC2q/r4JEl45p1RbLlT/e4qzq1aJgF0AzI8=
before_install:
- sudo apt-get install -y libmemcached-dev
install: pip install -r requirements.txt
script: export SECRET_KEY = $SECRET_KEY
  coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py
  test blogengine
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: m4uqxUqEWB32gzke9iQ7hQP7MTnRdVTvqYnZVsM/jG4kzuxk9nEWdVBdO2Anlib2DtT7zxZaoDv2BLQnDfNfyaMxv79wRcbkiTOXFFNYm+bsDE3nI56jGdXmY7do9Aq23fkr32RbEyktttmmRCrGPL1pULs0xC9vcCTU/rCy+cutPVvv80Bd1FkVXgNKAuZU6A9/ivqLS1qLM2/7IiTdavKHR5LAlU3tbIfFQoGlIWaMKl6d05221xfw4EbYoAm5E/5K2gY2mmw6guPPrB+XDYB0507makqMOHEh06u0M3HFw/+/iIyrC87pPMcyQl7Z57i9Q8PzCTie9z81tsy+Sclc+KFxTYTct48bf2+4EpdCs82uzry7j27DFGyfFoyPFr2m0c4kH9SqniYAwxUYUjp0nLcqY+I/xP7WovD83ILxrGlnbgTHlG4wIroVxbAA+TPRm38dYh8R1743xdIKjAI9Pun64tusfT5aHdFlAgsTwOXbG8abT0fkFUH6UFf7WzxgOOWG37twxaMLTMUM2MYUdpymYHyxYZK+MRX6doG4pFKJ2tHqhKsYZAvwWYywtVIsIbtp/M09ypklvukqUQnJTDxBhAdlvv7j9WnPfd4aelLvCzAs8DhG2aRWUgb8u/BaBeZOqMBBAfomoZG0MjwnLeWRVBUoZ29eu+Fbmvw=
  app: akll
