language: python
python:
- 3.4.3
services: memcached
before_install:
- sudo apt-get install -y libmemcached-dev
install: pip install -r requirements.txt
env:
  global:
    secure: CJWJTPh40RL46h8EyhX4pADH/+QgVJcKvPm2WJw3k0fxYOArzVNA4D7YKTKfpDaXCGsNa1Io991xI6BrDWTv35X1NLM+jMOVdJKmfF0PI3ds37GFd1WfzZ3fCta6cfn7uqvGvXvQvpQoTGxOuoi4grOuB8Ixq8qEppdTG0yYHVx24tKIMOnfKMTbCeD7aIIVPrDpKUchzuABpNnJXGZfVbRxwWz1xI0AoGE51WKxNbCtuwHt440IF/8uebwpaqvKyO01e0KpQ6YY8NOIsjcxMmc+Lt0FOxjPifSzQbsI+S1+YjgL1WILltoZ0VymmTdVFdpvpzA+omLfqf2ZYNGrE2Tr21mKTS+G48ZbHVEOf86PNsl0dB/4oZGX+/APw1XvTxsLXdiUKIrCsNVEMYDionyWNta6OegKXBhQ+dg7rhF99d3lifpNX4i0+pEBbEH4hEEeTDvVgdhAsxjAQRI0d83G6vhzf+CMcKCUIFtp9TirSp+kz4igFM/f87KfzlGMPJDl/EJcVv/2Ye8i2GX9Tdv95NKa3LTbd0wd0BlzqQ47joaWAbw1iBAGqGKMoNBTmWHwebjDaBdhEIRvAfvRRWW67QLXhT3NV7vm6AlcUh/JXm4lZ0s9L9BPoz8+6a3qkw04B5rqrqyL8qhMkjp5V9xAEaGLl9o9vvK/H8BNx+I=
script:
- export SECRET_KEY=$SECRET_KEY
- coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py
  test blogengine
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: m4uqxUqEWB32gzke9iQ7hQP7MTnRdVTvqYnZVsM/jG4kzuxk9nEWdVBdO2Anlib2DtT7zxZaoDv2BLQnDfNfyaMxv79wRcbkiTOXFFNYm+bsDE3nI56jGdXmY7do9Aq23fkr32RbEyktttmmRCrGPL1pULs0xC9vcCTU/rCy+cutPVvv80Bd1FkVXgNKAuZU6A9/ivqLS1qLM2/7IiTdavKHR5LAlU3tbIfFQoGlIWaMKl6d05221xfw4EbYoAm5E/5K2gY2mmw6guPPrB+XDYB0507makqMOHEh06u0M3HFw/+/iIyrC87pPMcyQl7Z57i9Q8PzCTie9z81tsy+Sclc+KFxTYTct48bf2+4EpdCs82uzry7j27DFGyfFoyPFr2m0c4kH9SqniYAwxUYUjp0nLcqY+I/xP7WovD83ILxrGlnbgTHlG4wIroVxbAA+TPRm38dYh8R1743xdIKjAI9Pun64tusfT5aHdFlAgsTwOXbG8abT0fkFUH6UFf7WzxgOOWG37twxaMLTMUM2MYUdpymYHyxYZK+MRX6doG4pFKJ2tHqhKsYZAvwWYywtVIsIbtp/M09ypklvukqUQnJTDxBhAdlvv7j9WnPfd4aelLvCzAs8DhG2aRWUgb8u/BaBeZOqMBBAfomoZG0MjwnLeWRVBUoZ29eu+Fbmvw=
  app: akll
